version: '3'

services:
  healthy-bot-db:
    container_name: healthy-bot-db
    image: postgres:alpine
    hostname: healthy-bot-db
    ports:
      - "5402:5402"
    environment:
      - POSTGRES_DB=healthybot
      - POSTGRES_USER=healthybot
      - POSTGRES_PASSWORD=healthybot
    volumes:
      - healthy-bot-db:/var/lib/postgresql/data
    command: -p 5402

  healthy-bot:
    container_name: healthy-bot
    hostname: healthy-bot
    depends_on:
      - healthy-bot-db
    build: .
    env_file:
      - .env

volumes:
  healthy-bot-db:
