version: '3'

services:
  healthy-bot-db:
    image: postgres:alpine
    hostname: healthybot-db
    ports:
      - "5400:5400"
    environment:
      - POSTGRES_DB=healthybot
      - POSTGRES_USER=healthybot
      - POSTGRES_PASSWORD=healthybot
    volumes:
      - healthy-bot-db:/var/lib/postgresql/data
    command: -p 5400

  healthy-bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  healthy-bot-db:
