services:
  healthy-bot-db:
    container_name: healthy-bot-db
    image: postgres:alpine
    hostname: healthy-bot-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=healthybot
      - POSTGRES_USER=healthybot
      - POSTGRES_PASSWORD=healthybot
    volumes:
      - healthy-bot-db:/var/lib/postgresql/data
    restart: unless-stopped

  healthy-bot:
    container_name: healthy-bot
    image: ghcr.io/buracc/healthy-bot/healthy-bot:latest
    hostname: healthy-bot
    depends_on:
      - healthy-bot-db
    build: .
    env_file:
      - .env
    volumes:
      - healthy-bot:/healthybot/data
    restart: unless-stopped

volumes:
  healthy-bot-db:
  healthy-bot: